version: '2'
services:
    smartbank-app:
        image: smartbank
        external_links:
            - smartbank-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/smartbank?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8008:8008
    smartbank-mysql:
        extends:
            file: mysql.yml
            service: smartbank-mysql
